### ISSUE TITLE
sample svg file

### ISSUE THREAD

**Issue by ghost** [lvoegtlin/svg_to_page#2]
@lvoegtlin Can you upload a sample svg file so that we can test on.
because the svg files  that I am testing on all fail.

I know that you are reading this, does it take much to reply back?

**Comment by lvoegtlin** [comment]
As I write in the description, this script converts coordinate SVG files (path-based polygons) to page XML. The SVG file you provide is not a coordinate SVG file and so this is not working. 

If you want to do something else with it, you can use this script as a template and adapt it.

**Comment by ghost** [comment]
@lvoegtlin is there a way to convert a PDF file to a coordinate SVG file?

**Comment by lvoegtlin** [comment]
in the data folder, there is one

**Comment by ghost** [comment]
@lvoegtlin is there a way to convert PDF to coordinate SVG file?

**Comment by lvoegtlin** [comment]
I would not be aware of such a script

**Comment by ghost** [comment]
@lvoegtlin what about PDF to Page-xml?

**Comment by lvoegtlin** [comment]
perhaps ocropus has something. Else I don't know.
